import type { Metadata } from "next";
import "@/app/ui/globals.css";
import "@/app/ui/auth/Login.css";
export const metadata: Metadata = {
  title: "Lalatrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="manifest" href="/manifest.json" />
      <meta name="theme-color" content="#000000" />
      <body>
        <div className="phone-shell">{children}</div>
      </body>
    </html>
  );
}
